### ISSUE TITLE
Getting issue with NuGet package reference

### ISSUE THREAD

**Issue by JeniJMS** [GeorgDangl/xbim-meets-angular#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Xbim.Geometry.3.0.24\build\net45\Xbim.Geometry.targets.	XbimDemoWebApp	D:\Projects\angular\XbimWebDemo-master\XbimDemoWebApp\XbimDemoWebApp.csproj	362

**Comment by GeorgDangl** [comment]
Hi JeniJMS,

can you share your project or the contents of `XbimDemoWebApp.csproj`? This error message indicates that you need to restore your NuGet package references.

**Comment by JeniJMS** [comment]
https://github.com/andyward/XbimWebDemo

**Comment by GeorgDangl** [comment]
Hmm this repository here is a different one. It's an Angular SPA application with an ASP.NET Core backend, the one you've linked to seems to be an ASP.NET MVC project. They're not related actually=)
