### ISSUE TITLE
How can i show grid with xBim

### ISSUE THREAD

**Issue by mobdev313** [GeorgDangl/xbim-meets-angular#2]
How can i show grid in viewer with xBim project?

**Comment by GeorgDangl** [comment]
I'm not sure about how to display a grid, as I haven't used that before.
If there's an `IfcGrid` in the file, it should be displayed like any other entity. Otherwise, you could ask directly in the https://github.com/xBimTeam/XbimWebUI repository, since I'm only using the viewer here.

**Comment by mobdev313** [comment]
Thanks for advice.
