### ISSUE TITLE
Any possibilities to Solve "This operation requires IIS integrated pipeline mode. " issue?  *without changing pipeline mode

### ISSUE THREAD

**Issue by castronelson** [GeorgDangl/xbim-meets-angular#6]

**Comment by castronelson** [comment]
I have developed the project which has the progress bar to showing the exact response from server side by using Signal R technology,This works fine in integrated pipeline mode where as classic mode not working. But I need to get resolved by in classic pipeline mode itself.
Could you please Suggest your opinion in the same way.

thank you in advance.

**Comment by GeorgDangl** [comment]
Is your project publicly available for viewing the code? Are you hosting on Azure or on a self-hosted IIS installation? If you're using IIS, which version? Is this helpful: https://stackoverflow.com/questions/22313167/this-operation-requires-iis-integrated-pipeline-mode ?

**Comment by castronelson** [comment]
Not public .and also not hosted in Azure. It is Local project and created IIS with pipeline mode as classic .Here IIS version 10.0 (Self hosted IIS).

**Comment by GeorgDangl** [comment]
I think this is something that you should ask in the appropriate Microsoft repositories, this seems like something with your IIS and website setup. I haven't seen that error before, neither on .NET Core or on the classic framework.

**Comment by castronelson** [comment]
Thank you.. :)

**Comment by GeorgDangl** [comment]
I'm sorry I couldn't be more helpful😊
